### ISSUE TITLE
Branches have diverged for assignment 2 since the autograder was configured. Can no longer commit and push changes.

### ISSUE THREAD

**Issue by Elvin-Liu237** [comp426-2022-fall/a02#13]
Your branch and 'origin/main' have diverged,
and have 4 and 6 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

I have tried every version of git pull but all of them have gotten me nowhere.

**Comment by smelliskay** [comment]
This is likely an issue/discrepancy with local commits rather than staged modification. It is also possible you'll need to rebase.  ("git rebase origin/master")

https://stackoverflow.com/questions/2452226/master-branch-and-origin-master-have-diverged-how-to-undiverge-branches

On the link I just sent is a bunch of different fixes. Work through some of these and if you are still having issues comment back.
